#!/usr/bin/env node
// Copies runtime assets (WASM codecs, ONNX Runtime) from temporarily installed
// npm packages into the repo, then regenerates VENDOR.md with SHA-256 hashes.
//
// Run manually, only when deliberately upgrading a vendored asset:
//   node scripts/vendor.mjs
//
// Nothing here runs during `npm run build`; the build uses the committed files.

import { execSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { cpSync, existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

// Hand-written type declarations for the Emscripten glue modules. The upstream
// .d.ts files reference a global EmscriptenWasm namespace we don't vendor.
const emscriptenDts = (encodeSignature) => `// Generated by scripts/vendor.mjs
export type EncoderModule = {
  encode: ${encodeSignature};
};
declare const moduleFactory: (options?: Record<string, unknown>) => Promise<EncoderModule>;
export default moduleFactory;
`;

const jsquashEncodeSignature =
  '(data: Uint8Array | Uint8ClampedArray, width: number, height: number, options: Record<string, unknown>) => Uint8Array | null';

const oxipngDts = `// Generated by scripts/vendor.mjs
export function optimise(data: Uint8Array, level: number, interlace: boolean, optimizeAlpha: boolean): Uint8Array;
declare const init: (moduleOrPath?: RequestInfo | URL | Response | BufferSource | WebAssembly.Module) => Promise<unknown>;
export default init;
`;

/**
 * @typedef {{ from: string; to?: string; dts?: string }} FileSpec
 * @typedef {{ name: string; version: string; license: string; url: string; dest: string; files: FileSpec[] }} PackageSpec
 */

/** @type {PackageSpec[]} */
const packages = [
  {
    name: '@jsquash/jpeg',
    version: '1.6.0',
    license: 'Apache-2.0 (wrapper); MozJPEG: IJG + BSD-3-Clause + zlib',
    url: 'https://github.com/jamsinclair/jSquash/tree/main/packages/jpeg',
    dest: 'src/vendor/jsquash/jpeg@1.6.0',
    files: [
      { from: 'codec/enc/mozjpeg_enc.js', dts: emscriptenDts(jsquashEncodeSignature) },
      { from: 'codec/enc/mozjpeg_enc.wasm' },
      { from: 'LICENSE' },
      { from: 'codec/LICENSE.codec.md' },
    ],
  },
  {
    name: '@jsquash/webp',
    version: '1.5.0',
    license: 'Apache-2.0 (wrapper); libwebp: BSD-3-Clause',
    url: 'https://github.com/jamsinclair/jSquash/tree/main/packages/webp',
    dest: 'src/vendor/jsquash/webp@1.5.0',
    files: [
      { from: 'codec/enc/webp_enc.js', dts: emscriptenDts(jsquashEncodeSignature) },
      { from: 'codec/enc/webp_enc.wasm' },
      { from: 'codec/enc/webp_enc_simd.js', dts: emscriptenDts(jsquashEncodeSignature) },
      { from: 'codec/enc/webp_enc_simd.wasm' },
      { from: 'LICENSE' },
      { from: 'codec/LICENSE.codec.md' },
    ],
  },
  {
    name: '@jsquash/avif',
    version: '2.1.1',
    license: 'Apache-2.0 (wrapper); libavif: BSD-2-Clause; libaom: BSD-2-Clause + AOM patent license',
    url: 'https://github.com/jamsinclair/jSquash/tree/main/packages/avif',
    dest: 'src/vendor/jsquash/avif@2.1.1',
    files: [
      { from: 'codec/enc/avif_enc.js', dts: emscriptenDts(jsquashEncodeSignature) },
      { from: 'codec/enc/avif_enc.wasm' },
      { from: 'LICENSE' },
    ],
  },
  {
    name: '@jsquash/oxipng',
    version: '2.3.0',
    license: 'Apache-2.0 (wrapper); oxipng: MIT',
    url: 'https://github.com/jamsinclair/jSquash/tree/main/packages/oxipng',
    dest: 'src/vendor/jsquash/oxipng@2.3.0',
    files: [
      { from: 'codec/pkg/squoosh_oxipng.js', dts: oxipngDts },
      { from: 'codec/pkg/squoosh_oxipng_bg.wasm' },
      { from: 'LICENSE' },
      { from: 'codec/LICENSE.codec.md' },
    ],
  },
  {
    name: 'onnxruntime-web',
    version: '1.30.0',
    license: 'MIT (Copyright (c) Microsoft Corporation)',
    url: 'https://github.com/microsoft/onnxruntime/tree/v1.30.0/js/web',
    dest: 'public/vendor/ort@1.30.0',
    // The WebGPU build: one asyncify wasm serves both the WebGPU and the WASM (CPU) providers.
    files: [
      { from: 'dist/ort.webgpu.min.mjs' },
      { from: 'dist/ort-wasm-simd-threaded.asyncify.mjs' },
      { from: 'dist/ort-wasm-simd-threaded.asyncify.wasm' },
    ],
    // The npm package ships no LICENSE file; take it from the tagged source.
    extraDownloads: [{ url: 'https://raw.githubusercontent.com/microsoft/onnxruntime/v1.30.0/LICENSE', to: 'LICENSE' }],
  },
  {
    name: 'libheif-js',
    version: '1.23.2',
    license: 'LGPL-3.0 (libheif and its libde265 decoder)',
    url: 'https://github.com/catdad-experiments/libheif-js',
    // Served as a separate, unmodified file (LGPL: users can swap in their own build) and only
    // loaded when a HEIC/HEIF image arrives in a browser that can't decode it natively.
    dest: 'public/vendor/libheif@1.23.2',
    files: [{ from: 'libheif-wasm/libheif-bundle.mjs' }, { from: 'LICENSE' }, { from: 'libheif-wasm/LICENSE', to: 'LICENSE.libheif' }],
  },
  {
    name: 'pdfjs-dist',
    version: '6.3.289',
    license: 'Apache-2.0 (pdf.js); fonts, CMaps, OpenJPEG, JBIG2 and QCMS under the LICENSE files next to them',
    url: 'https://github.com/mozilla/pdf.js',
    // Loaded by the page only when a PDF arrives, to render its pages as images.
    dest: 'public/vendor/pdfjs@6.3.289',
    files: [
      // The legacy build: the modern one needs the newest JS features (e.g. Math.sumPrecise).
      { from: 'legacy/build/pdf.min.mjs' },
      { from: 'legacy/build/pdf.worker.min.mjs' },
      { from: 'LICENSE' },
      { from: 'standard_fonts', to: 'standard_fonts' },
      { from: 'cmaps', to: 'cmaps' },
      { from: 'iccs', to: 'iccs' },
      ...['jbig2.wasm', 'openjpeg.wasm', 'qcms_bg.wasm', 'LICENSE_JBIG2', 'LICENSE_OPENJPEG', 'LICENSE_PDFJS_JBIG2', 'LICENSE_PDFJS_OPENJPEG', 'LICENSE_PDFJS_QCMS', 'LICENSE_QCMS'].map(
        (file) => ({ from: `wasm/${file}`, to: `wasm/${file}` }),
      ),
    ],
  },
];

/**
 * Assets that don't come from npm. The script only hashes them for VENDOR.md;
 * how they were produced is documented in scripts/vendor-manual.md.
 * @type {{ name: string; dir: string }[]}
 */
const manualAssets = [{ name: 'ISNet general-use, 8-bit weights', dir: 'public/models/isnet-general-use-wq8' }];

const sha256 = (path) => createHash('sha256').update(readFileSync(path)).digest('hex');

const listFiles = (dir) =>
  readdirSync(dir).flatMap((entry) => {
    const full = join(dir, entry);
    return statSync(full).isDirectory() ? listFiles(full) : [full];
  });

const vendorPackages = () => {
  const tmp = mkdtempSync(join(tmpdir(), 'localcrop-vendor-'));
  try {
    writeFileSync(join(tmp, 'package.json'), '{"private":true}');
    const specs = packages.map((p) => `${p.name}@${p.version}`).join(' ');
    console.log(`Installing ${specs} into ${tmp}`);
    execSync(`npm install --no-save --ignore-scripts --no-audit --no-fund ${specs}`, { cwd: tmp, stdio: 'inherit' });

    for (const pkg of packages) {
      const srcDir = join(tmp, 'node_modules', pkg.name);
      const destDir = join(root, pkg.dest);
      rmSync(destDir, { recursive: true, force: true });
      mkdirSync(destDir, { recursive: true });
      for (const file of pkg.files) {
        const target = join(destDir, file.to ?? file.from.split('/').pop());
        // Recursive: some entries are whole folders (pdf.js fonts, CMaps).
        cpSync(join(srcDir, file.from), target, { recursive: true });
        if (file.dts) writeFileSync(target.replace(/\.js$/, '.d.ts'), file.dts);
      }
      for (const download of pkg.extraDownloads ?? []) {
        execSync(`curl -fsSL -o "${join(destDir, download.to)}" "${download.url}"`, { stdio: 'inherit' });
      }
      console.log(`Vendored ${pkg.name}@${pkg.version} → ${pkg.dest}`);
    }
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }
};

const renderVendorMd = () => {
  const sections = packages.map((pkg) => {
    const destDir = join(root, pkg.dest);
    const rows = listFiles(destDir)
      .map((file) => `| \`${relative(destDir, file).split(sep).join('/')}\` | ${statSync(file).size} | \`${sha256(file)}\` |`)
      .join('\n');
    return `### ${pkg.name}@${pkg.version}

- **Source package:** \`${pkg.name}\` (npm)
- **Exact version:** ${pkg.version}
- **License:** ${pkg.license}
- **Source URL:** ${pkg.url}
- **Location:** \`${pkg.dest}/\`

| File | Bytes | SHA-256 |
|---|---:|---|
${rows}
`;
  });

  const manualPath = join(root, 'scripts', 'vendor-manual.md');
  const manualText = existsSync(manualPath) ? readFileSync(manualPath, 'utf8') : '';
  const manualHashes = manualAssets
    .filter((asset) => existsSync(join(root, asset.dir)))
    .map((asset) => {
      const dir = join(root, asset.dir);
      const rows = listFiles(dir)
        .map((file) => `| \`${relative(dir, file).split(sep).join('/')}\` | ${statSync(file).size} | \`${sha256(file)}\` |`)
        .join('\n');
      return `#### Files: ${asset.name} (\`${asset.dir}/\`)\n\n| File | Bytes | SHA-256 |\n|---|---:|---|\n${rows}\n`;
    })
    .join('\n');
  const manual = manualText ? `\n${manualText}\n${manualHashes}` : '';

  return `# Vendored runtime assets

Generated by \`node scripts/vendor.mjs\`. Do not edit by hand; edit the script
(or \`scripts/vendor-manual.md\` for assets not sourced from npm) and re-run it.

These files are committed so that a rebuild months from now produces the same
app, with no runtime or build-time network access to package registries or CDNs.

Only the **single-threaded encoder** builds are vendored: GitHub Pages can't send
COOP/COEP headers, so \`SharedArrayBuffer\` (and therefore WASM threads) is unavailable.
ONNX Runtime likewise runs with \`numThreads = 1\`. The jSquash JS wrappers are *not*
vendored — they pull in \`wasm-feature-detect\` and multi-thread code paths. \`src/worker/codecs.ts\` drives the Emscripten glue directly,
using the same default options as the upstream wrappers.

${sections.join('\n')}${manual}`;
};

const main = () => {
  const onlyDocs = process.argv.includes('--docs-only');
  if (!onlyDocs) vendorPackages();
  writeFileSync(join(root, 'VENDOR.md'), renderVendorMd());
  console.log('Wrote VENDOR.md');
};

main();
